### ISSUE TITLE
Error: write EPIPE at errnoException

### ISSUE THREAD

**Issue by ajashton** [mapbox/node-mbtiles#28]
Via support:

> I am trying to reduce the size of my mbtiles file. Via MBPipe I run
> mbpipe 'advpng -z -4' file.mbtiles On a 8 MB file this works as expected, but as soon as the mbtiles file exceed something about 30 MB the process fails with.
> 
> Error: write EPIPE at errnoException (net.js:776:11) at Object.afterWrite (net.js:594:19)

Any ideas on this?

**Comment by mapsam** [comment]
The mbpipe command was removed in 0.3.0 https://github.com/mapbox/node-mbtiles/commit/a98037dbdfd19f6cf5a72737cf338654686f734e - closing!
