### ISSUE TITLE
What happened to mbpipe?

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/node-mbtiles#31]
It was removed in commit a98037dbdfd19f6cf5a72737cf338654686f734e
Has it been moved to a different library?

**Comment by mapsam** [comment]
mbpipe was removed in 0.3.0 https://github.com/mapbox/node-mbtiles/commit/a98037dbdfd19f6cf5a72737cf338654686f734e and we do not have plans to replace them right now. Cheers
