### ISSUE TITLE
Docs for tilelive say start/stopWriting must be reentrant, but they aren't

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/node-mbtiles#56]
Calling startWriting twice, then stopWriting once, then putTile results in an error `Error: MBTiles not in write mode` but according to the documentation for tilelive.js this should work.

see https://github.com/mapbox/tilelive.js/blob/master/API.md

**Comment by mapsam** [comment]
Confirmed with the following test case:

```javascript
var MBTiles = require('@mapbox/mbtiles');
var fs = require('fs');

new MBTiles('./new.mbtiles', function(err, mbtiles) {
  mbtiles.startWriting(function(err) {
    if (err) throw err;
    mbtiles.startWriting(function(err) {
      if (err) throw err;
      mbtiles.stopWriting(function(err) {
        var tile = fs.readFileSync('./0-0-0.png');
        mbtiles.putTile(0, 0, 0, tile, function(err) {
          if (err) throw err;
          console.log('done writing');
        });
      });
    });
  });
});
```

**Comment by jingsam** [comment]
I don't know how to solve this issue. @JesseCrocker @mapsam Do you encounter some problems because of this issue?

**Comment by JesseCrocker** [comment]
@jingsam i've written code that uses this module that specifically knows about this behavior and works around it. As for fixing it, it seems like it ought to be possible to keep track of the number of calls to startWriting, and then decrement that count when stopWriting is called, and only close the database if the start count is 0.

**Comment by mapsam** [comment]
@jingsam I personally haven't encountered issues with this, but just wrote the quick script above to confirm the issue. Sounds like a counter would be the most straightforward way forward as proposed by @JesseCrocker. 

A more complicated approach would be to initialize a new, internal, sqlite3 instance for each `startWriting` operation and be able to close/commit that instance with a stopWriting. This would be some sort of sqlite3 exec map. I'm not certain this would provide any added benefit that a simple counter wouldn't.
