### ISSUE TITLE
Support for node.js 4.2.1?

### ISSUE THREAD

**Issue by Brutusn** [mapbox/node-mbtiles#58]
Hello,

The npm install mbtiles is failing with node.js v4.2.1. (Actually it's the sqlite package that is failing). When will the new node version be supported?

**Comment by springmeyer** [comment]
node-mbtiles will need to be tagged to use at least node-sqlite3 3.1.x: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#310

**Comment by springmeyer** [comment]
v0.8.1 is now published that supports node 4.x
