### ISSUE TITLE
Indexing in mbtiles

### ISSUE THREAD

**Issue by divya1c** [mapbox/node-mbtiles#61]
Hi!

I am using a tilelive server to serve tiles for my mapbox gl front end. I am not sure if this is the right place to ask, but is it possible to insert custom indexes in my mbtiles, for faster access? Or are there any other methods for faster access of features in mbtiles?

A little background on what I am trying to do :
I am trying to have a filter on my mapbox gl side, and since I have too many features, it is not very efficient.

Thanks! Any help will be very much appreciated.

**Comment by jingsam** [comment]
mbtiles are just sqlite tables. you can just do what sqlite supports.
