### ISSUE TITLE
Silent crash on large putTiles statement

### ISSUE THREAD

**Issue by jedateach** [mapbox/node-mbtiles#62]
I'm investigating the limitations of this mbtiles package.

When I add 640,000 tiles using mbtiles.putTile, the command understandably takes a long time, but it then exits (after 16 minutes) with no error.

I've tried outputting node-sqlite3 sql log using the [debug on trace callback](https://github.com/mapbox/node-sqlite3/wiki/Debugging#databaseontrace-callback), and the last thing output in my cli is `COMMIT`, then sits blankly for most of that 16 min, suggesting to me that perhaps the sqlite3 binary might be doing something.
- Why might this be happening?
- Why is there no debug messaging? Is there anything further I can enable?
- Could I be hitting sqlite3 limits? https://www.sqlite.org/limits.html
- Is this issue better suited for https://github.com/mapbox/node-sqlite3?

**Comment by jingsam** [comment]
Close for now. If you still encounter the same issue. Please reopen it.
