### ISSUE TITLE
Allow in-memory sqlite db for testing

### ISSUE THREAD

**Issue by jedateach** [mapbox/node-mbtiles#64]
It would be great to make use of the special ':memory:' sqlite location to create databases in memory. The package currently expects there to be a file existing to report various stats.

**Comment by jingsam** [comment]
in-memory mbtiles are technique approachable. Could you describe your use case with in-memory mbtiles?

**Comment by jingsam** [comment]
Close for now. If you still want this feature. Welcome send use a PR.
