### ISSUE TITLE
Inconsistent scheme in getInfo

### ISSUE THREAD

**Issue by hannesj** [mapbox/node-mbtiles#65]
Currently mbtiles [always reports](https://github.com/mapbox/node-mbtiles/blob/master/lib/mbtiles.js#L227) it's scheme as tms, even though it [swaps the z coordinate in getTile](https://github.com/mapbox/node-mbtiles/blob/master/lib/mbtiles.js#L149) in order to serve the tiles in xyz scheme.

**Comment by mapsam** [comment]
Thanks @hannesj for reporting this. Apologies for the delay.

@mapbox/core-tech @kkaefer this and the PR #81 seem pretty valid, considering when _putting_ and _getting_ tiles, they are in XYZ but they are stored as TMS which the mbtiles-spec calls for. Should the metadata field reflect the storage format or the retrieval format?

**Comment by springmeyer** [comment]
👍  to reporting `scheme` as xyz. Though I'm not familiar off hand with what tools respond to this `scheme` metadata, we should double check whether tilelive or other consumers might break.
