### ISSUE TITLE
Vector mbtiles schema

### ISSUE THREAD

**Issue by edpop** [mapbox/node-mbtiles#67]
Hello.
When a user makes .mbtiles by the [tippecanoe](https://github.com/mapbox/tippecanoe) tool, it creates just one table - [tiles](https://github.com/mapbox/tippecanoe/blob/1.16.3/mbtiles.cpp#L46).
But I can't stream any data into this file because of the **putTile** method uses other tables (map and images), and also can't create a new file with this specification by **mbtiles** library.
I guess we need to wait for [2.0 spec](https://github.com/mapbox/mbtiles-spec/pull/46)?

**Comment by ericfischer** [comment]
I'm not sure how the vector tile 2.0 spec will help with this. If you have two tilesets and want to combine them, you can use `tile-join` to combine the features from both tilesets into one new one.

**Comment by edpop** [comment]
I mean, there is no way to work with other schema, than [this one](https://github.com/mapbox/node-mbtiles/blob/v0.9.0/lib/schema.sql), where **tiles** table is a view. I made vector mbtiles by [tilelive-http](https://github.com/mojodna/tilelive-http) + [mbtiles](https://github.com/mapbox/node-mbtiles), it worked, but pbf format is not permitted in current [spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md#content-1), also [this schema](https://github.com/mapbox/tippecanoe/blob/1.16.3/mbtiles.cpp#L46) is more optimized (one table vs 2 tables + view).

**Comment by ericfischer** [comment]
The only reason Tippecanoe creates `tiles` as a table rather than as a view is because I just [copied the SQL from mb-util](https://github.com/mapbox/mbutil/blob/master/mbutil/util.py#L21) and that's what it does. If it would be more useful to have it be a view, I can change it to be a view.

**Comment by edpop** [comment]
No, personally I don't see any reason for this deoptimization, especially I don't see tables **map**, **images** and **grid\*** in a spec. I thought, that vector tiles will have a different scheme, than [this](https://github.com/mapbox/node-mbtiles/blob/v0.9.0/lib/schema.sql) and current lib should have a some option like _type (pbf)_ or/and _version_ to determine tables schema and some methods as **putTile()** accordingly.
