### ISSUE TITLE
mbpipe bug?

### ISSUE THREAD

**Issue by tristen** [mapbox/node-mbtiles#9]
I wanted to create some post-processing on a map using mbpipe: Running this command: 

```
mbpipe 'convert -size 256x256 xc:white png:- -alpha Off -compose Copy_Opacity -composite -monochrome -alpha On png:-' layer.mbtiles
```

The status meter ran pretty fast for 18mb file. It declared 'Pipe complete' but it seemingly made no change to the layer.

**Comment by mapsam** [comment]
Closing, since `mbpipe` was removed in 0.3.0 https://github.com/mapbox/node-mbtiles/commit/a98037dbdfd19f6cf5a72737cf338654686f734e
