### ISSUE TITLE
listTiles

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/node-mbtiles#95]
It would be nice to have an API which listed zxy tiles in the MBTiles, without that you can't know which specific zxy values to pass to getTile without querying the whole globe.

**Comment by jingsam** [comment]
I can not get your ideas. What is the specific use case? can you explain more?

**Comment by andrewharvey** [comment]
The idea was to have a way to list out which exact z/x/y tiles are in the MBTiles, yes you could look at the metadata for the bounds and min/max zooms, but in cases where perhaps the tiles covered a polygon instead of a bounds, then you can't know which tiles exist through node-mbtiles.

I don't actually need this anymore so I'll close the ticket, but the workaround I came up with was to simply run a select * from tiles; query through sqlite3 directly. Feel free to re-open if there is interest in implementing.
