### ISSUE TITLE
Promises API

### ISSUE THREAD

**Issue by sanfilippopablo** [mapbox/node-mbtiles#98]
Hello!

Any chances to introduce a promise-compatible API?

**Comment by jingsam** [comment]
You can try this:
```js
const {promisify} = require('util')
const MBtiles = 

async run () => {
  const mbtiles = await new (promisify(MBTiles))(mbtilesPath)
  
 const info = await promisify(mbtiles.getInfo.bind(mbtiles))()
}
```

Note that as `mbtiles.getTile` has more than one parameter in callback. You can only get `tile` and missing `headers`:
```js
const tile = await promisify(mbtiles.getTile.bind(mbtiles))(z, x, y)
```

**Comment by sanfilippopablo** [comment]
Yeah, that's what I was doing, but this issue is more about natively supporting it. If there's any interest I could maybe put a PR.

**Comment by jingsam** [comment]
node-mbtiles implements tilelive interface. It would better to add promise  support in tilelive side.

**Comment by sanfilippopablo** [comment]
Fair enough. Closing this. Thanks!
